name: Setup Terraform via GitHub Actions
# Source: https://github.com/marketplace/actions/hashicorp-setup-terraform

# on: [push, pull_request]
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: Check terraform file are formatted correctly
    runs-on: ubuntu-latest
    
    env:
      PR_TITLE: Apply terraform fmt changes
      PR_BODY: GitHub Action that rewrites Terraform Config files to a canonical format and style
      PR_BRANCH: automated-terraform-fmt

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      
      # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Run Terraform fmt
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -no-color
        continue-on-error: true
      
      # Create the Pull Request and save the PR URL as a variable
      - name: Create Pull Request
        id: create_pr
        run: |
          make_pr=$(gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base $PR_BRANCH)
          echo "MAKE_PR=make_pr >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Merge the Pull Request using the saved URL from create_pr
      - name: Merge Pull Request
        id: merge_pr
        run: echo "url is ${{ steps.create_pr.outputs.make_pr }}"
#         run: gh pr merge --delete-branch $PR_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

#       - name: Create Pull Request
#         id: create_pr
#         uses: peter-evans/create-pull-request@v5
#         # https://github.com/marketplace/actions/create-pull-request
#         with:
#           commit-message: terraform fmt
#           title: Reformat terraform files
#           body: Update terraform files to canonical format using `terraform fmt`
#           branch: automated-terraform-fmt
        
#       - name: Enable Pull Request Automerge
#         if: steps.create_pr.outputs.pull-request-operation == 'created'
#         # https://github.com/peter-evans/enable-pull-request-automerge
#         uses: peter-evans/enable-pull-request-automerge@v3
#         with:
#           pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
#           merge-method: squash
