name: Setup Terraform via GitHub Actions
# Source: https://github.com/marketplace/actions/hashicorp-setup-terraform

# on: [push, pull_request]
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: Check terraform file are formatted correctly
    runs-on: ubuntu-latest
    
    env:
      REPO_FORK: origin
      REPO_NAME: vsphere-tf
      PR_TITLE: Apply terraform fmt changes
      PR_BODY: GitHub Action that rewrites Terraform Config files to a canonical format and style
      PR_BRANCH: automated-terraform-fmt

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      
      # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Create branch
        run: |
          gh auth login
          gh repo fork
          gh repo clone $REPO_NAME
          cd $REPO_NAME
          git checkout -b $PR_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run Terraform fmt
      - name: Terraform fmt
        id: fmt
        run: |
          terraform fmt -recursive -no-color
        continue-on-error: true
        
      - name: Commit changes
        run: |
          git add .
          git commit -m "$PR_TITLE"

      - name: Push changes
        run: |
          git push --set-upstream $REPO_FORK $PR_BRANCH
      
      # Create the Pull Request and save the PR URL as a variable
      - name: Create Pull Request
        id: create_pr
        run: |
          make_pr=$(gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base $PR_BRANCH)
          echo "MAKE_PR=$make_pr" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Merge the Pull Request using the saved URL from create_pr
      - name: Merge Pull Request
        id: merge_pr
        run: |
          git fetch --all
          gh pr merge ${{ steps.create_pr.outputs.make_pr }} --delete-branch --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
