name: Setup Terraform via GitHub Actions
# Source: https://github.com/marketplace/actions/hashicorp-setup-terraform

# on: [push, pull_request]
on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: Check terraform file are formatted correctly
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      
      # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -no-color terraform
        continue-on-error: true

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        # https://github.com/marketplace/actions/create-pull-request
        with:
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          branch: automated-terraform-fmt
        
      - name: Enable Pull Request Automerge
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        # https://github.com/peter-evans/enable-pull-request-automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: squash
